%% This is a mermaid file (https://github.com/mermaid-js/mermaid)

flowchart TD
    sub_DAF4_character_subroutine --> bra_DB14_skip
    bra_DB14_skip --> bra_DB1B_skip
    bra_DB1B_skip --> bra_DB20_skip
    bra_DB20_skip --> bra_DB2A_skip
    bra_DB2A_skip --> loc_DB44
    loc_DB44 --> bra_DB52_skip
    bra_DB52_skip --> bra_DB60_skip
    bra_DB60_skip --> bra_DB6A
    bra_DB60_skip --> loc_DD87_jump_subroutine
    loc_DD87_jump_subroutine --> loc_DED2
    loc_DED2 --> loc_DE86
    loc_DE86 --> loc_DBC2
    bra_DB6A --> bra_DB93_skip
    bra_DB93_skip --> bra_DBB0_skip
    bra_DBB0_skip --> bra_DBEF
    loc_DBC2 --> loc_E132
    bra_DBEF --> loc_E132